services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
    working_dir: /anvil/labs
    ports:
      - "8545:8545"
    command: anvil
    volumes:
      - .:/anvil/labs

